name: Deploy
on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container: sphinxdoc/sphinx
    steps:
      - name: Install git 🔧
        shell: bash
        run: |
          apt-get update
          apt-get install -y git

      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          repository: 'Concordium/concordium.github.io'
          ref: 'main'

      - name: Install 🔧
        shell: bash
        run: |
          apt-get install -y graphviz rsync
          pip3 install -r requirements.txt

      - name: Build 🛠
        shell: bash
        run: ./scripts/build.sh

      - name: Deploy Developer Documentation 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: build-academy
          clean: true

